services:
  db:
    image: postgres:16
    container_name: toko_db
    environment:
      POSTGRES_USER: toko
      POSTGRES_PASSWORD: toko_dev_pw
      POSTGRES_DB: tokobangunan
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toko -d tokobangunan"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: toko_redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: toko_mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # web UI

volumes:
  db_data:
