"""add ai fields to orders and order_items

Revision ID: 0e4f2932ac09
Revises: 78a1122a0a07
Create Date: 2026-09-08 18:44:01.591405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4f2932ac09'
down_revision: Union[str, Sequence[str], None] = '78a1122a0a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('raw_name', sa.String(length=200), nullable=True))
    op.add_column('order_items', sa.Column('matched_score', sa.Float(), nullable=True))
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('orders', sa.Column('intent', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('extraction_confidence', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'needs_review')
    op.drop_column('orders', 'extraction_confidence')
    op.drop_column('orders', 'intent')
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'matched_score')
    op.drop_column('order_items', 'raw_name')
    # ### end Alembic commands ###
