"""add raw_messages and conversations

Revision ID: 3e1d033c5368
Revises: 3f4ffe8d35ee
Create Date: 2026-09-09 10:37:43.956514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e1d033c5368'
down_revision: Union[str, Sequence[str], None] = '3f4ffe8d35ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('wa_id', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_messages_wa_id'), 'raw_messages', ['wa_id'], unique=False)
    op.create_table('conversations',
    sa.Column('wa_id', sa.String(length=40), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('active_order_id', sa.Integer(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('wa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    op.drop_index(op.f('ix_raw_messages_wa_id'), table_name='raw_messages')
    op.drop_table('raw_messages')
    # ### end Alembic commands ###
