"""add rate_counters

Revision ID: 3f4ffe8d35ee
Revises: ebbfed70464e
Create Date: 2026-09-09 10:20:50.208120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4ffe8d35ee'
down_revision: Union[str, Sequence[str], None] = 'ebbfed70464e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_counters',
    sa.Column('bucket_key', sa.String(length=120), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('bucket_key', 'window_start')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_counters')
    # ### end Alembic commands ###
