"""add step_types and workflow_steps

Revision ID: 815084221e38
Revises: a3169e562741
Create Date: 2026-09-08 20:47:34.456373

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "815084221e38"
down_revision: str | Sequence[str] | None = "a3169e562741"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "step_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("default_sla_minutes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "workflow_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("step_type_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=True),
        sa.Column("sla_target_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "elapsed_minutes",
            sa.Numeric(precision=12, scale=2),
            sa.Computed("EXTRACT(EPOCH FROM (completed_at - assigned_at)) / 60", persisted=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["step_type_id"],
            ["step_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_steps_order_id"), "workflow_steps", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_steps_step_type_id"), "workflow_steps", ["step_type_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_steps_step_type_id"), table_name="workflow_steps")
    op.drop_index(op.f("ix_workflow_steps_order_id"), table_name="workflow_steps")
    op.drop_table("workflow_steps")
    op.drop_table("step_types")
    # ### end Alembic commands ###
