"""add departments, workflow_types, workflow_steps indexes

Revision ID: 90e2689dc92f
Revises: 3e1d033c5368
Create Date: 2026-09-09 11:13:35.446099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e2689dc92f'
down_revision: Union[str, Sequence[str], None] = '3e1d033c5368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workflow_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('orders', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('workflow_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_department_id'), 'orders', ['department_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'workflow_types', ['workflow_type_id'], ['id'])
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    op.create_index('ix_ws_pending', 'workflow_steps', ['assignee_id', 'assigned_at'], unique=False, postgresql_where=sa.text('completed_at IS NULL'))
    op.create_index('ix_ws_steptype_assigned', 'workflow_steps', ['step_type_id', 'assigned_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ws_steptype_assigned', table_name='workflow_steps')
    op.drop_index('ix_ws_pending', table_name='workflow_steps', postgresql_where=sa.text('completed_at IS NULL'))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_department_id'), table_name='orders')
    op.drop_column('orders', 'workflow_type_id')
    op.drop_column('orders', 'department_id')
    op.drop_table('workflow_types')
    op.drop_table('departments')
    # ### end Alembic commands ###
