"""add report_runs

Revision ID: c9e3fc56afed
Revises: 90e2689dc92f
Create Date: 2026-09-09 11:40:30.221953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e3fc56afed'
down_revision: Union[str, Sequence[str], None] = '90e2689dc92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_runs',
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('report_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_runs')
    # ### end Alembic commands ###
